name: Mise Tester

on:
  pull_request:
      
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install Tool Versions
      uses: jdx/mise-action@latest
      with:
        experimental: true
    - name: test
      run: |
        ls -la
        pwd
        ./test.sh