name: Mise Tester

on:
  push:
    branches:
      - 'main'
  pull_request:
      
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install once
      uses: jaxxstorm/action-install-gh-release@6096f2a2bbfee498ced520b6922ac2c06e990ed2
      with:
        repo: jaredallard/once
    - name: Install Tool Versions
#      uses: jdx/mise-action@v3
      uses: jdx/mise-action@13abe502c30c1559a5c37dff303831bab82c9402

      with:
        experimental: true
        # reshim: true
    - name: Install Stencil
      uses: rgst-io/stencil-action@34abb7be7ca3847f233bd9c38f1da71b30556c35
      with:
        github-token: ${{ github.token }}
        version: 'latest'
    # - name: Run stencil
    #   shell: bash
    #   run: stencil
