name: Mise Tester

on:
  pull_request:
      
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install Tool Versions
#      uses: jdx/mise-action@v3
      uses: jdx/mise-action@13abe502c30c1559a5c37dff303831bab82c9402

      with:
        experimental: true
        # reshim: true
    - name: test
      run: |
        ls -la
        pwd
        ./test.sh